#!/usr/bin/env bash

# Exit after the first error. This way, a keyboard interrupt for one verifier
# process will prevent others from running as well.
set -e
for net in fc1 fc2 fc3 fc4 fc5
do
	for k in 0 1;
	do
		echo Evaluating network net${k}_${net}
		for spec in `ls ../test_cases/net${k}_${net}`
		do
			python verifier.py --net net${k}_${net} --spec ../test_cases/net${k}_${net}/${spec}
		done
	done
done
