#!/usr/bin/env bash

# Exit after the first error. This way, a keyboard interrupt for one verifier
# process will prevent others from running as well.
set -e

TEST_CASES_DIR="../test_cases"

while IFS=, read net spec expected; do
    echo -n "$net @ $spec: "
    python verifier.py \
        --net $net \
        --spec "$TEST_CASES_DIR/$net/$spec"
done < "$TEST_CASES_DIR/gt.txt"
